# Generated by Django 3.2.8 on 2024-02-21 20:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_cliente_cuenta_movimiento_movimientoi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='cedula_cli',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='codigo_cta',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='fecha_mov',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='tipo_mov',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libreria.cuenta'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo_movimiento',
            field=models.CharField(default='Ingreso', max_length=100),
        ),
        migrations.DeleteModel(
            name='MovimientoI',
        ),
    ]
