# Generated by Django 3.2.8 on 2024-02-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_auto_20240221_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
