# Generated by Django 3.2.8 on 2024-02-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_alter_movimiento_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
