# Generated by Django 3.2.8 on 2024-02-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_alter_movimiento_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='id_u',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
