# Generated by Django 3.2.8 on 2024-02-21 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_alter_movimiento_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='adm_cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_adm', models.CharField(default='', max_length=10, unique=True)),
                ('cedula_cli', models.CharField(default='', max_length=12)),
                ('fecha_creacion_cta', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
