# Generated by Django 3.2.8 on 2024-02-21 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0013_auto_20240221_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='saldo',
        ),
    ]
