# Generated by Django 3.2.8 on 2024-02-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0016_alter_movimiento_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
