# Generated by Django 3.2.8 on 2024-03-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0019_cliente_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_cli', models.CharField(default='', max_length=12, unique=True)),
                ('contraseña', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
