# Generated by Django 3.2.8 on 2024-04-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0020_auto_20240229_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='id_u',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cedula',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='chequera',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
